# application.yml (config-data)
server:
  port: 8081
spring:
  application:
    name: ms-examen-service

  # Perfil común para Config Server
  cloud:
    config:
      server:
        git:
          uri: https://tu-repo-en-github.com/usuario/config-data
          clone-on-start: true
        native:
          search-locations: classpath:/config

---
# Configuración para ms-estudiante (usando MySQL)
spring:
  config:
    activate:
      on-profile: ms-estudiante
  application:
    name: ms-estudiante
  datasource:
    url: jdbc:mysql://localhost:3306/ms-estudiante
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  springdoc:
    api-docs:
      enabled: true
    swagger-ui:
      enabled: true
      path: /doc/swagger-ui.html

---
# Configuración para ms-curso (usando PostgreSQL)
# spring:
#   config:
#     activate:
#       on-profile: ms-curso
#   application:
#     name: ms-curso
#   datasource:
#     url: jdbc:postgresql://localhost:5432/ms-curso
#     driver-class-name: org.postgresql.Driver
#     username: postgres
#     password: tu_password
#   jpa:
#     hibernate:
#       ddl-auto: update
#     show-sql: true
#   springdoc:
#     api-docs:
#       enabled: true
#     swagger-ui:
#       enabled: true
#       path: /doc/swagger-ui.html

---
# Configuración para ms-curso (usando H2)
spring:
  config:
    activate:
      on-profile: ms-curso
  application:
    name: ms-curso
datasource:

  url: jdbc:h2:mem:ms_curso
  driver-class-name: org.h2.Driver
  username: sa
  password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  springdoc:
    api-docs:
      enabled: true
    swagger-ui:
      enabled: true
      path: /doc/swagger-ui.html
